### PR TITLE
BaSP-MR-119: fixed validation admin, messages for consistency

### PR DESCRIPTION
**Pull request by Eugeniagassman**
I fixed validation in admin for the password, corrected the validation for name and last name in admin, and fixed messages in all components for more consistency

### CODE REVIEW

**Comment by Eugeniagassman** [comment]
[[SUGGESTION]Unifying response messages all entities.](https://trello.com/c/fukQ4Ebn/117-suggestionunifying-response-messages-all-entities)

**Comment by Eugeniagassman** [comment]
[[BUG] Validation Admins for 'Password'.](https://trello.com/c/02guspdb/119-bug-validation-admins-for-password)

**Comment by Eugeniagassman** [comment]
[[BUG] Validation admins for 'name' and 'last name'](https://trello.com/c/9ac9xeUc/118-bug-validation-admins-for-name-and-last-name)

**Review by Tilajc — APPROVED** [review]
You did a pretty good job!

**Comment by Flor-Farruggia** [comment]
Hi! The validations in inputs are really good! But it still does not consistent enough, try to do all the message with equal message! But in general is a really good job!

**Pull request merged**
